language: ruby

cache: bundler

rvm:
  - 2.2
  - 2.1
  - 2.0
  - rbx-2
  - jruby-19mode
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: rbx-2
    - rvm: 2.0
      env: CONCURRENCY=celluloid-io

git:
  submodules: false

env:
  - CONCURRENCY=celluloid-io
  - CONCURRENCY=faye-websocket
